run:
  timeout: 5m
  go: "1.21"

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/f00b455/golang-template
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - godot
    - godox
    - goerr113
    - gomnd
    - ifshort
    - interfacer
    - ireturn
    - lll
    - maintidx
    - maligned
    - nlreturn
    - nonamedreturns
    - paralleltest
    - prealloc
    - scopelint
    - testpackage
    - thelper
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - funlen
        - lll
    - path: features/
      linters:
        - gomnd
        - goconst
        - funlen
        - lll

  exclude-use-default: false
  exclude:
    - 'shadow: declaration of "(err|ctx)" shadows declaration at line \d+'